// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: hello1

#ifndef _HELLO1_UI_H
#define _HELLO1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_pic001_png);    // assets/pic001.png
LV_IMG_DECLARE(ui_img_pic002_png);    // assets/pic002.png
LV_IMG_DECLARE(ui_img_pic003_png);    // assets/pic003.png
LV_IMG_DECLARE(ui_img_pic004_png);    // assets/pic004.png
LV_IMG_DECLARE(ui_img_pic005_png);    // assets/pic005.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
